language: php
php:
  - '7.3'
  - '7.4'

matrix:
  allow_failures:
    - php: '7.4'

addons:
  mariadb: '10.2'

# Only run on the base branches
branches:
  only:
    - master
    - develop

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
  - sudo apt-get update
  - composer self-update

install:
  - mysql -e 'create database IF NOT EXISTS uk_plugin;' -uroot

before_script:
  - cp .env.travis .env
  - composer install
  - php artisan optimize
  - php artisan migrate
  - php artisan passport:install
  - php artisan db:seed

script:
  - ./vendor/bin/phpunit
  - php script/lint-dependencies.php
