language: php
php:
  - '7.3'
  - '7.4'

matrix:
  allow_failures:
    - php: '7.4'

addons:
  mariadb: '10.2'

# Only run on the base branches
branches:
  only:
    - master
    - develop

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
  - sudo apt-get update

install:
  - mysql -e 'create database IF NOT EXISTS uk_plugin;' -uroot
  - cp .env.travis .env
  - composer self-update
  - composer install

before_script:
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install
  - php artisan db:seed
  - php artisan config:clear

script:
  - ./vendor/bin/phpunit
  - php script/lint-dependencies.php
